apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-express-demo-app-deployment
  namespace: express
  labels:
    app: node-express-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-express-demo-app
  template:
    metadata:
      labels:
        app: node-express-demo-app
    spec:
      containers:
      - name: node-app
        image: ganesh1326/express:latest
        ports:
        - containerPort: 3000

