apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-demo-app-deployment
  namespace: express
  labels:
    app: node-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-demo-app
  template:
    metadata:
      labels:
        app: node-demo-app
    spec:
      containers:
      - name: node-app
        image: ganesh1326/node-demo-app:02
        ports:
        - containerPort: 3000

