apiVersion: v1
kind: Service
metadata:
  name: node-express-demo-app-service
  namespace: express
spec:
  selector:
    app: node-express-demo-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
